CREATE TABLE dbo.SKU
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Code AS 's' + CAST(ID AS NVARCHAR(255)) UNIQUE,
    Name NVARCHAR(255),
);

CREATE TABLE dbo.Family
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    SurName NVARCHAR(255),
    BudgetValue DECIMAL
);

CREATE TABLE dbo.Basket
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
	ID_SKU INT,
	ID_FAMILY INT,
	Quantity INT NOT NULL CHECK (Quantity >= 0),
	Value DECIMAL NOT NULL CHECK (Value >= 0),
    PurchaseDate DATETIME DEFAULT GETDATE(),
	DiscountValue DECIMAL,
	FOREIGN KEY (ID_SKU) REFERENCES dbo.SKU (ID),
	FOREIGN KEY (ID_FAMILY) REFERENCES dbo.Family (ID)
);